#!/bin/bash

echo "Running WartRemover..."
sbt compile
# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
  echo "WartRemover found issues. Please fix them before committing."
  exit 1
fi
echo "All checks passed!dsafghgdsa"
