on:
  pull_request_review:
    types:
      - submitted
      - dismissed

jobs:
  ff:
    runs-on: ubuntu-latest
    steps:
      - name: check type
        run: echo ${{ github.event.review.state }}
#        uses: endre-spotlab/fast-forward-js-action@2.1
